version: "3.8"
services:
  api:
    image: kikurage3133/test_mygopen_api:secretfree-test
    command: uv run uvicorn api.main:app --host 0.0.0.0 --port 8888
    ports:
      - "8889:8888"
    environment:
      TZ: Asia/Taipei
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_ACCOUNT: ${MYSQL_ACCOUNT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_ACCOUNT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  mysql_data:
